apiVersion: apps/v1
kind: Deployment
metadata:
  name: python
spec:
  selector:
    matchLabels:
      app: python
  replicas: 3
  template:
    metadata:
      labels:
        app: python
    spec:
      containers:
      - name: python
        image: 1104ravi409/newimage:latest
        ports:
        - containerPort: 80
        env:
          - name: PORT
            value: "8080"
